apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: build-a-bot
    tier: backend
spec:
  selector:
    matchLabels:
      app: build-a-bot
      tier: backend
  template:
    metadata:
      labels:
        app: build-a-bot
        tier: backend
    spec:
      containers:
        - name: build-a-bot
          image: localhost:32000/build-a-bot-api:latest
          #image: build-a-bot-api:1.0
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: backend-app-settings 
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8085
            initialDelaySeconds: 15 # The initialDelaySeconds field tells the kubelet that it should wait 5 seconds before performing the first probe.
            timeoutSeconds: 2 # Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.
            periodSeconds: 5 # The periodSeconds field specifies that the kubelet should perform a liveness probe every 5 seconds.
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 8085
            initialDelaySeconds: 15 # The initialDelaySeconds field tells the kubelet that it should wait 5 seconds before performing the first probe.
            timeoutSeconds: 2 # Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.
            periodSeconds: 5 # The periodSeconds field specifies that the kubelet should perform a liveness probe every 5 seconds.

