apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  selector:
    app: build-a-bot
    tier: backend
