apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31705 # this will expose exteranlly localhost:31704 for site
      targetPort: 8085 # this is the port on the container
      protocol: TCP
      name: http
    - port: 443
      nodePort: 32454
      protocol: TCP
      name: https
  selector:
    app: build-a-bot
    tier: backend
