# Name the node stage "builder"
FROM node:10.15.0
ENV CGO_ENABLED 0 

WORKDIR /app/

# Copy the source code into the container
COPY . .

WORKDIR /app/web/

# Deleting these if they are grabbed from my local
RUN rm -rf node_modules 
RUN rm -rf package-lock.json

# install node modules and build assets 
RUN npm install 

CMD ["npm", "run", "serve"] 