apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 8081 # navigate to http://localhost:8081 for site
      targetPort: 80
  selector:
    tier: frontend
