apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 80 # port on the container?
  selector:
    tier: frontend
