apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: build-a-bot
    tier: frontend
spec:
  selector:
    matchLabels:
      app: build-a-bot
      tier: frontend
  template:
    metadata:
      labels:
        app: build-a-bot
        tier: frontend
    spec:
      containers:
        - name: build-a-bot
          #image: localhost:32000/build-a-bot-web:registry
          image: build-a-bot-web:1.0
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
          env:
            - name: VUE_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-app-settings
                  key: VUE_APP_API_URL
