apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31704 # this will expose exteranlly localhost:31704 for site
      targetPort: 80 # this is the port on the container
      protocol: TCP
      name: http
    - port: 443
      nodePort: 32453
      protocol: TCP
      name: https
  selector:
    app: build-a-bot
    tier: frontend
