# Assuming this file is ran at the root
# ex: sudo docker-compose -f ./api/docker/compose.dev.yml up --build
version: "3.3"
services:
  server:
    build:
      context: ../../
      dockerfile: api/docker/Dockerfile.dev
    working_dir: /app/api
    volumes:
      - type: bind
        source: ../../
        target: /app/
    ports:
      - 8085:8085  
      - 2345:2345 # debugging endpoint
  web:
    build:
      context: ../../
      dockerfile: web/docker/Dockerfile.dev
    working_dir: /app/web 
    volumes:
      - type: bind
        source: ../../web
        target: /app/web
    environment:
      - npm_config_unsafe_perm=true
    ports:
      - 4000:8080   
    depends_on:
      - server
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
    external: true