# Assuming this file is ran at the root
# ex: sudo docker-compose -f ./api/docker/compose.dev.yml up --build
version: "3.3"
services:
  server:
    build:
      context: ../../
      dockerfile: api/docker/Dockerfile.dev
    working_dir: /app/api
    volumes:
      - type: bind
        source: ../../
        target: /app/
    ports:
      - 8085:8085  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
    external: true