apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:  # We dont need to worry about converting to base64
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: example
  POSTGRES_DB: postgres
  DB_HOST: build-a-bot-postgres
  DB_DRIVER: postgres
  DB_USER: postgres
  DB_PASSWORD: example
  DB_NAME: postgres
  DB_PORT: "5432"