name: Bump version
on:
  push:
    branches:
      - "release/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        run: ./github/workflows/version.sh
